import "Pages\Items.idl";

namespace WinMount.App.Pages {
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page {
        MainPage();

        MainViewModel ViewModel{ get; };
    };
}
