import "Items\Items.idl";

namespace WinMount.App.Pages {
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page {
        MainPage();

        WinMount.App.Items.MainViewModel ViewModel{ get; };
    };
}
